[package]
name = "phenix-tui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
base64 = { workspace = true }
clap = { workspace = true }
image = { workspace = true }
mermaid-text = { workspace = true }
phenix-acp = { path = "../phenix-acp" }
phenix-acp-backend = { path = "../phenix-acp-backend" }
phenix-frontend-config = { path = "../phenix-frontend-config" }
phenix-runtime-api = { path = "../phenix-runtime-api" }
phenix-ui-core = { path = "../phenix-ui-core" }
phenix-ui-lua = { path = "../phenix-ui-lua" }
phenix-ui-runtime = { path = "../phenix-ui-runtime" }
ratatui = { workspace = true }
ratatui-image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shell-words = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-bash = { workspace = true }
tree-sitter-highlight = { workspace = true }
tree-sitter-javascript = { workspace = true }
tree-sitter-json = { workspace = true }
tree-sitter-lua = { workspace = true }
tree-sitter-nix = { workspace = true }
tree-sitter-python = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-typescript = { workspace = true }

[lib]
path = "src/lib.rs"

[[bin]]
name = "phenix"
path = "src/main.rs"
