[package]
name = "phenix-acp-backend"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
agent-client-protocol-conductor.workspace = true
agent-client-protocol-rmcp.workspace = true
base64.workspace = true
blocking.workspace = true
futures.workspace = true
phenix-acp = { path = "../phenix-acp" }
phenix-runtime-api = { path = "../phenix-runtime-api" }
serde_json.workspace = true
schemars.workspace = true
serde.workspace = true
shell-words.workspace = true
tokio.workspace = true
