[package]
name = "phenix-backend-native"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
base64.workspace = true
futures.workspace = true
genai.workspace = true
oauth2.workspace = true
phenix-backend = { path = "../phenix-backend" }
phenix-core = { path = "../phenix-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
