local map = phenix.keymap.set

map("global", "<C-d>", phenix.action.quit, { desc = "Quit Phenix" })
map("global", "<C-q>", phenix.action.quit, { desc = "Quit Phenix" })
map("global", "<C-c>", phenix.action.abort, { desc = "Interrupt the selected run" })
map("global", "<Esc>", phenix.action.abort, { desc = "Interrupt or close the active surface" })
map("global", "<C-l>", phenix.action.login, { desc = "Open authentication" })
map("global", "<C-m>", phenix.action.models, { desc = "Open model picker" })
map("global", "<C-r>", phenix.action.sessions, { desc = "Open session picker" })
map("global", "<C-o>", phenix.action.toggle_details, { desc = "Toggle detailed mode" })
map("global", "<Tab>", function() phenix.ui.focus.move("next") end, { desc = "Focus next pane" })
map("global", "<S-Tab>", function() phenix.ui.focus.move("previous") end, { desc = "Focus previous pane" })

map("input", "<CR>", phenix.action.submit, { desc = "Submit prompt" })
map("input", "<S-CR>", function() phenix.input.insert("\n") end, { desc = "Insert newline" })
map("input", "<C-CR>", phenix.action.steer, { desc = "Steer active run" })
map("input", "<M-CR>", phenix.action.follow_up, { desc = "Queue follow-up" })
map("input", "<BS>", phenix.input.backspace, { desc = "Delete previous character" })
map("input", "<Del>", phenix.input.delete, { desc = "Delete character" })
map("input", "<Left>", phenix.input.move_left, { desc = "Move cursor left" })
map("input", "<Right>", phenix.input.move_right, { desc = "Move cursor right" })
map("input", "<Up>", phenix.input.history_previous, { desc = "Previous input history" })
map("input", "<Down>", phenix.input.history_next, { desc = "Next input history" })

map("sidebar", "j", function() phenix.ui.pane.scroll("ui.sidebar", 1) end)
map("sidebar", "k", function() phenix.ui.pane.scroll("ui.sidebar", -1) end)
map("sidebar", ">", function() phenix.ui.pane.resize("ui.sidebar", "horizontal", 2) end)
map("sidebar", "<", function() phenix.ui.pane.resize("ui.sidebar", "horizontal", -2) end)

map("transcript", "j", function() phenix.ui.pane.scroll("ui.transcript", 1) end)
map("transcript", "k", function() phenix.ui.pane.scroll("ui.transcript", -1) end)
map("transcript", "<PageDown>", function() phenix.ui.pane.scroll("ui.transcript", 10) end)
map("transcript", "<PageUp>", function() phenix.ui.pane.scroll("ui.transcript", -10) end)

map("overlay", "<CR>", phenix.overlay.accept, { desc = "Accept selected item" })
map("overlay", "<Esc>", phenix.overlay.cancel, { desc = "Close overlay" })
map("overlay", "j", phenix.overlay.next, { desc = "Select next item" })
map("overlay", "k", phenix.overlay.previous, { desc = "Select previous item" })
map("overlay", "<Down>", phenix.overlay.next)
map("overlay", "<Up>", phenix.overlay.previous)
map("overlay", "<BS>", phenix.input.backspace)
